// Corpus de reforço em frases (pt-BR) para o INGramRepository (PRD §25, ADR-007/016).
// Fonte: frases motivacionais/filosóficas originais, de inspiração filosófica (estoicismo, existencialismo, mentalidade de crescimento),
// escritas para este projeto. Nenhuma é atribuída a um filósofo real, vivo ou contemporâneo — evitei citações verdadeiras
// (risco de reprodução de material protegido) e evitei fabricar frases com o nome de uma pessoa real (risco de desinformação).
// Uso pretendido: corpus de reforço para o `INGramRepository` (PRD §25), como uma fonte alternativa ou complementar
// ao corpus de português coloquial já previsto em `ADR-007`/`TASK-051`.

// Convenção (ADR-016): o conteúdo de reforço é normalizado para ASCII — diacríticos
// (á, ã, ç, é ...) são removidos para que a digitação não dependa de dead-key/composição
// no desktop. A lista abaixo mantém o texto original com acentos como fonte de verdade
// legível; `PT_BR_PHRASES` exporta a versão normalizada consumida pelo repositório.

const STARTER_PHRASES = [
  'A disciplina é a ponte entre a intenção e o resultado.',
  'Persistir não é insistir no erro, é continuar apesar do medo.',
  'Todo hábito começa como um ato incômodo repetido com paciência.',
  'Quem constrói devagar raramente precisa reconstruir do zero.',
  'A vontade forte nasce de pequenas escolhas repetidas todos os dias.',
  'Não é o talento que sustenta o caminho, é a rotina.',
  'Cair faz parte do processo, parar de levantar é a escolha.',
  'O esforço constante vence a inspiração que aparece só às vezes.',
  'Quem treina todos os dias já venceu quem treina só quando quer.',
  'A firmeza de propósito é mais rara do que a boa ideia.',
  'Continuar quando ninguém está vendo é onde o caráter se forma.',
  'A repetição paciente transforma o difícil em natural.',
  'Disciplina é escolher entre o que você quer agora e o que você quer de verdade.',
  'Nenhuma jornada longa se completa sem os passos pequenos e chatos.',
  'Manter o ritmo importa mais do que acelerar de vez em quando.',
  'A constância silenciosa produz mais do que o entusiasmo barulhento.',
  'Fazer o simples bem feito, todos os dias, é a base de tudo.',
  'Persistência é a arte de recomeçar sem drama.',
  'O compromisso com o processo pesa mais do que a promessa do resultado.',
  'Quem aprende a esperar aprende também a construir.',
  'A dedicação diária é invisível até o dia em que ela aparece inteira.',
  'Não é preciso ser perfeito, é preciso continuar aparecendo.',
  'A vontade que resiste ao cansaço é a que realmente conta.',
  'Cada repetição consciente vale mais do que dez feitas no automático.',
  'O caminho fica mais claro para quem já deu o próximo passo.',
  'A paciência com o próprio progresso é uma forma de disciplina.',
  'Manter o compromisso nos dias difíceis é o que separa o hábito do capricho.',
  'Fazer hoje o que ontem parecia impossível é o efeito discreto da prática.',
  'A constância é uma decisão que se renova a cada manhã.',
  'Ninguém domina algo sem antes ser ruim nisso por um bom tempo.',
  'O esforço sem direção cansa; o esforço com propósito constrói.',
  'Levantar de novo é sempre mais importante do que não ter caído.',
  'A prática séria é feita de dias comuns, não de momentos especiais.',
  'Aquilo que se pratica com regularidade deixa de exigir coragem.',
  'Segurar o próprio ritmo é mais sábio do que correr atrás do de outro.',
  'A firmeza tranquila rende mais do que o esforço ansioso.',
  'Todo domínio começa com o desconforto de ser iniciante.',
  'O hábito bem cuidado sustenta a pessoa nos dias sem motivação.',
  'Continuar é, na maior parte do tempo, a única virtude necessária.',
  'A repetição com atenção ensina o que a pressa nunca ensinaria.',
  'Nenhum progresso real acontece sem o tédio de treinar o básico.',
  'A disciplina tranquila é mais duradoura do que a força de vontade repentina.',
  'Persistir com calma rende mais do que insistir com ansiedade.',
  'O compromisso silencioso de cada dia é o que sustenta o grande resultado.',
  'Aprender a voltar ao trabalho depois de uma pausa é uma habilidade em si.',
  'A prática constante transforma esforço em naturalidade.',
  'Nem todo dia será bom, mas todo dia pode ser cumprido.',
  'O caminho se revela para quem continua andando mesmo sem ver o fim.',
  'A persistência quieta costuma valer mais do que o esforço espetacular.',
  'Fazer um pouco, mas fazer sempre, muda tudo com o tempo.',
  'Aprender é aceitar, por um instante, que você ainda não sabe.',
  'O erro bem observado ensina mais do que o acerto repetido sem atenção.',
  'Conhecimento que não muda a prática é apenas informação guardada.',
  'Toda pergunta boa vale mais do que uma resposta apressada.',
  'Aprender de verdade exige devagar antes de exigir rápido.',
  'Quem estuda com curiosidade aprende mais do que quem estuda por obrigação.',
  'O domínio de algo simples é mais valioso do que a superficialidade de muitas coisas.',
  'A prática consciente ensina o que a leitura sozinha não alcança.',
  'Errar no momento certo é parte essencial de aprender algo novo.',
  'Todo especialista já foi, um dia, alguém que não sabia nada daquilo.',
  'Estudar é também aprender a conviver com a própria confusão temporária.',
  'A curiosidade sincera abre mais portas do que a pressa por resultado.',
  'Aprender uma habilidade nova exige aceitar ser ruim nela por um tempo.',
  'O conhecimento aplicado vale mais do que o conhecimento apenas guardado.',
  'Rever o que já foi aprendido fortalece o que parecia esquecido.',
  'Cada dificuldade encontrada no estudo é também um mapa do que falta entender.',
  'Ensinar algo a alguém é uma das formas mais completas de aprender.',
  'A repetição espaçada ensina mais do que a repetição apressada.',
  'Todo aprendizado sólido nasce da disposição de recomeçar sem vergonha.',
  'Observar os próprios erros com calma é meio caminho para corrigi-los.',
  'A prática deliberada ensina mais em pouco tempo do que a prática distraída em muito tempo.',
  'Aprender é, também, aceitar que o progresso não é sempre linear.',
  'O hábito de perguntar "por quê" transforma informação em compreensão.',
  'Quem aprende devagar, mas com atenção, costuma aprender para sempre.',
  'A confusão inicial costuma ser sinal de que algo novo está sendo assimilado.',
  'Todo conhecimento útil começou como uma dúvida levada a sério.',
  'Aprender a errar sem se punir é parte do aprendizado em si.',
  'A prática guiada por atenção rende mais do que a prática guiada por pressa.',
  'Nenhuma habilidade nasce pronta, ela se revela aos poucos, com esforço.',
  'O estudo constante, mesmo em pequenas doses, supera o estudo intenso e raro.',
  'Toda dúvida bem formulada já é metade do caminho até a resposta.',
  'Aprender com calma evita ter que desaprender depois com pressa.',
  'A memória se fortalece com o uso, não apenas com a repetição.',
  'Observar como se erra ensina tanto quanto observar como se acerta.',
  'O aprendizado profundo pede tempo que a pressa não costuma oferecer.',
  'Cada novo conceito entendido cria espaço para o próximo.',
  'Praticar com atenção plena vale mais do que praticar por muito tempo distraído.',
  'A humildade de admitir não saber é o primeiro passo para aprender.',
  'Todo progresso no estudo é feito de pequenas correções acumuladas.',
  'Aprender é também aceitar que o domínio total nunca chega de vez.',
  'A prática regular transforma o que era difícil em algo natural.',
  'Quem revisa o que aprendeu retém mais do que quem apenas avança.',
  'O esforço de entender vale mais do que o esforço de decorar.',
  'Toda habilidade nova exige um período de desconforto produtivo.',
  'Aprender com paciência evita o cansaço de aprender com pressa.',
  'A curiosidade mantida viva é o motor mais durável do aprendizado.',
  'Cada erro corrigido com calma se transforma em conhecimento estável.',
  'O estudo feito com constância rende mais do que o estudo feito com intensidade ocasional.',
  'Compreender é sempre mais valioso do que apenas memorizar.',
  'Aprender bem é, no fundo, aprender a ter paciência consigo mesmo.',
  'A atenção plena transforma uma tarefa comum em um exercício de presença.',
  'Focar em uma coisa de cada vez rende mais do que tentar tudo ao mesmo tempo.',
  'A mente dispersa gasta energia sem produzir avanço real.',
  'Prestar atenção ao presente é a forma mais simples de melhorar qualquer prática.',
  'O foco verdadeiro exige abrir mão de outras coisas boas, por um tempo.',
  'Concentração não é ausência de pensamentos, é escolha do pensamento certo.',
  'Fazer uma coisa bem feita vale mais do que fazer três pela metade.',
  'A distração é o inimigo silencioso de qualquer progresso constante.',
  'Quem aprende a focar aprende também a descansar melhor depois.',
  'O silêncio interno é o espaço onde a atenção realmente floresce.',
  'Cada minuto de atenção plena vale mais do que uma hora distraída.',
  'Focar no processo tira o peso da ansiedade pelo resultado.',
  'A prática exige presença, não apenas tempo disponível.',
  'Manter o foco em tarefas pequenas prepara a mente para desafios maiores.',
  'A atenção treinada é uma habilidade tão real quanto qualquer outra.',
  'Observar o próprio pensamento é o primeiro passo para direcioná-lo.',
  'O foco constante em pequenas metas sustenta grandes conquistas.',
  'Estar presente na tarefa atual é mais produtivo do que pensar na próxima.',
  'A mente treinada em foco resiste melhor às interrupções do dia a dia.',
  'Fazer devagar, mas com atenção total, supera fazer rápido e distraído.',
  'A concentração é um músculo que se fortalece com prática regular.',
  'Cada distração evitada é um passo a mais na direção do objetivo.',
  'O silêncio ao redor ajuda, mas o silêncio interno é o que realmente importa.',
  'Focar no que está ao alcance das mãos evita a paralisia diante do todo.',
  'A atenção cuidadosa transforma erros pequenos em lições claras.',
  'Uma tarefa feita com presença total rende mais do que várias feitas pela metade.',
  'O foco constante é mais raro, e por isso mais valioso, do que o talento.',
  'Cada instante de distração custa mais tempo do que parece.',
  'A prática com atenção plena acelera o aprendizado de qualquer habilidade.',
  'Voltar a atenção para o presente, sempre que ela se perde, é o próprio exercício.',
  'O foco bem direcionado transforma esforço em progresso visível.',
  'Aprender a ignorar o irrelevante é parte essencial de qualquer foco real.',
  'A mente calma concentra melhor do que a mente apressada.',
  'Cada tarefa merece, por alguns minutos, atenção inteira e nada mais.',
  'O foco sustentado é o que separa o exercício sério do passatempo.',
  'Prestar atenção aos pequenos detalhes evita os grandes erros depois.',
  'A concentração profunda exige, antes de tudo, reduzir o ruído ao redor.',
  'Uma prática breve e concentrada vale mais do que uma longa e dispersa.',
  'O hábito de focar se constrói, como qualquer outro, com repetição paciente.',
  'Cada momento de atenção plena é também um momento de aprendizado mais rápido.',
  'A mente que aprende a voltar ao foco aprende também a se recuperar de distrações maiores.',
  'Focar em um objetivo claro evita o desgaste de correr em várias direções.',
  'A atenção bem treinada rende mais do que muitas horas mal aproveitadas.',
  'Cada interrupção aceita sem resistência custa mais tempo do que se imagina.',
  'O foco no presente é o único lugar onde o progresso realmente acontece.',
  'Uma mente treinada em atenção lida melhor com tarefas complexas.',
  'Reduzir distrações é, em si, uma forma de disciplina.',
  'A prática atenta, mesmo curta, supera a prática longa e desatenta.',
  'Cada retorno da mente ao foco fortalece a capacidade de se concentrar.',
  'O verdadeiro progresso nasce da atenção repetida sobre o que importa.',
  'O obstáculo revela mais sobre a pessoa do que a facilidade jamais revelaria.',
  'Toda dificuldade superada deixa uma capacidade nova no seu lugar.',
  'Enfrentar o difícil de frente costuma doer menos do que evitá-lo por muito tempo.',
  'O que parece impossível hoje costuma ser apenas desconhecido ainda.',
  'Cada barreira vencida ensina algo que nenhuma facilidade poderia ensinar.',
  'A força real aparece justamente quando a situação exige mais do que se tem.',
  'Superar um obstáculo não é eliminá-lo, é aprender a atravessá-lo.',
  'O medo do desafio costuma ser maior do que o desafio em si.',
  'Toda superação começa com a decisão de continuar apesar da dúvida.',
  'O caminho mais difícil, quando percorrido, deixa a marca mais duradoura.',
  'Cada dificuldade enfrentada com calma se torna menor do que parecia.',
  'A resistência interna é, muitas vezes, maior do que o obstáculo externo.',
  'Vencer um desafio pequeno prepara a mente para os desafios maiores.',
  'O esforço para superar algo difícil constrói confiança verdadeira, não emprestada.',
  'Toda barreira tem, em algum ponto, uma passagem que ainda não foi vista.',
  'A persistência diante do obstáculo é o que transforma dificuldade em experiência.',
  'Cada tentativa que falha reduz a distância até a tentativa que funciona.',
  'O obstáculo que parece grande de longe costuma ficar menor de perto.',
  'Superar algo difícil exige menos força e mais constância do que se imagina.',
  'A dificuldade encarada com paciência raramente permanece do mesmo tamanho.',
  'Todo desafio vencido deixa a pessoa mais preparada para o próximo.',
  'O primeiro passo diante do obstáculo é sempre o mais pesado.',
  'Cada obstáculo contornado com criatividade ensina uma lição que a facilidade nunca ensinaria.',
  'A coragem para começar já resolve boa parte da dificuldade.',
  'Toda superação real é feita de pequenas resistências vencidas, uma a uma.',
  'O cansaço da luta é temporário; a força adquirida com ela, não.',
  'Encarar o obstáculo com calma evita que ele pareça maior do que é.',
  'Cada dificuldade vencida com paciência se transforma em capacidade permanente.',
  'O que hoje exige esforço extremo, amanhã pode exigir apenas atenção.',
  'Toda barreira superada revela uma versão mais capaz de quem a enfrentou.',
  'A persistência silenciosa costuma vencer obstáculos que a pressa não consegue.',
  'Cada tentativa, mesmo malsucedida, aproxima mais do resultado do que a inércia.',
  'O obstáculo evitado continua no caminho; o obstáculo enfrentado, não.',
  'Superar exige menos heroísmo e mais disposição para tentar de novo.',
  'A dificuldade encarada de perto costuma ser menor do que a imaginada de longe.',
  'Cada desafio vencido deixa um pouco mais de confiança para o próximo.',
  'O esforço sustentado supera obstáculos que a força repentina não alcança.',
  'Toda superação verdadeira exige tempo, não apenas vontade momentânea.',
  'A calma diante do obstáculo rende mais soluções do que a pressa.',
  'Cada barreira encarada com paciência ensina algo sobre os próprios limites.',
  'O caminho mais curto para superar algo é, muitas vezes, começar por ele.',
  'A resistência ao desconforto inicial costuma ser o maior obstáculo de todos.',
  'Toda dificuldade tem um tamanho real e um tamanho imaginado; raramente são iguais.',
  'Enfrentar um obstáculo pequeno hoje evita que ele cresça amanhã.',
  'A superação constante, mesmo em passos pequenos, muda o resultado no longo prazo.',
  'Cada obstáculo vencido com calma fortalece a confiança para o próximo desafio.',
  'O medo do fracasso costuma pesar mais do que o fracasso em si.',
  'Toda dificuldade enfrentada de perto perde parte do peso que carregava de longe.',
  'A perseverança diante do obstáculo é, no fim, mais decisiva do que o talento.',
  'Cada barreira superada com paciência se torna, mais tarde, uma fonte de confiança.',
  'A coragem não é ausência de medo, é agir apesar dele.',
  'Toda mudança real começa com uma ação pequena e desconfortável.',
  'Esperar o momento perfeito costuma ser uma forma discreta de adiar.',
  'Agir com incerteza é mais valioso do que esperar por certezas que talvez nunca cheguem.',
  'O primeiro passo, mesmo hesitante, já é mais do que a intenção parada.',
  'A coragem cresce na prática, não na espera por sentir-se pronto.',
  'Toda ação corajosa parece exagerada até o momento em que é tomada.',
  'Decidir é, muitas vezes, mais difícil do que executar.',
  'O medo de errar impede mais progresso do que o erro em si.',
  'Agir com o que se tem agora vale mais do que esperar ter tudo perfeito.',
  'A coragem discreta de tentar de novo é mais rara do que parece.',
  'Cada decisão tomada com clareza reduz o peso da indecisão seguinte.',
  'O risco calculado costuma valer mais do que a segurança que não leva a lugar nenhum.',
  'Toda ação corajosa começa com a aceitação de que o resultado é incerto.',
  'Adiar por medo custa mais, no longo prazo, do que agir e ajustar depois.',
  'A coragem de começar de novo é tão importante quanto a de começar pela primeira vez.',
  'Agir apesar da dúvida é o que diferencia intenção de mudança real.',
  'Cada pequena ação corajosa prepara terreno para decisões maiores.',
  'O medo, quando encarado, costuma ser menor do que parecia de longe.',
  'Toda mudança significativa exige, em algum momento, sair do que é confortável.',
  'A hesitação prolongada custa mais energia do que a ação decidida.',
  'Agir com o que é possível hoje evita a paralisia diante do ideal distante.',
  'Cada decisão tomada com coragem fortalece a confiança para a próxima.',
  'O primeiro movimento, mesmo pequeno, já rompe a inércia que impedia o avanço.',
  'Toda coragem verdadeira aparece na ação, não apenas na intenção declarada.',
  'Agir diante da incerteza é aceitar que nem tudo pode ser garantido antes.',
  'A espera excessiva pelo momento ideal costuma custar mais do que o risco de agir cedo.',
  'Cada decisão corajosa, mesmo pequena, muda a direção de algo maior.',
  'O medo de julgamento impede mais tentativas do que o próprio risco de errar.',
  'Toda ação tomada com clareza vale mais do que um plano perfeito nunca executado.',
  'A coragem de mudar de direção é tão válida quanto a de seguir em frente.',
  'Agir apesar do desconforto é o que separa intenção de resultado.',
  'Cada passo dado com incerteza ainda é mais valioso do que nenhum passo.',
  'O adiamento constante é, muitas vezes, medo disfarçado de prudência.',
  'Toda decisão difícil fica mais leve depois de tomada, mesmo que o caminho continue incerto.',
  'A coragem para pedir ajuda é tão importante quanto a coragem para agir sozinho.',
  'Agir com o pouco que se sabe hoje é melhor do que esperar saber tudo.',
  'Cada tentativa corajosa, mesmo imperfeita, ensina mais do que a espera cautelosa.',
  'O medo de começar costuma ser maior do que o esforço de já estar no meio do caminho.',
  'Toda ação tomada com intenção clara vale mais do que reação apressada sem direção.',
  'A coragem cotidiana, feita de pequenas decisões, sustenta mudanças duradouras.',
  'Agir apesar da dúvida é, no fundo, confiar mais no processo do que no resultado imediato.',
  'Cada decisão corajosa tomada hoje facilita a próxima decisão difícil de amanhã.',
  'O risco de tentar e ajustar supera o risco de nunca começar.',
  'Toda mudança de rumo corajosa começa com admitir que o caminho atual não serve mais.',
  'A coragem de errar em público é rara, mas essencial para o progresso real.',
  'Agir com convicção, mesmo incerta, vale mais do que a inação segura.',
  'Cada obstáculo enfrentado com coragem ensina mais do que qualquer teoria sobre superação.',
  'O primeiro passo corajoso costuma ser o mais difícil e o mais decisivo.',
  'Toda ação tomada apesar do medo fortalece a capacidade de agir na próxima vez.',
  'Conhecer os próprios limites é o primeiro passo para superá-los com inteligência.',
  'A calma para observar a si mesmo vale mais do que a pressa por se definir.',
  'Todo autoconhecimento exige aceitar partes de si que preferimos ignorar.',
  'Observar as próprias reações ensina mais do que julgar as reações dos outros.',
  'A honestidade consigo mesmo é o alicerce de qualquer mudança real.',
  'Conhecer os próprios padrões é o primeiro passo para poder escolher diferente.',
  'Toda mudança duradoura começa com a observação sincera do que já existe.',
  'A paciência consigo mesmo é tão importante quanto a paciência com os outros.',
  'Reconhecer um erro próprio exige mais coragem do que apontar o erro alheio.',
  'O autoconhecimento cresce mais na prática do que na reflexão isolada.',
  'Observar sem julgar é o primeiro passo para entender de verdade.',
  'Toda pessoa carrega padrões que só a atenção cuidadosa consegue revelar.',
  'Aceitar as próprias limitações é diferente de se acomodar com elas.',
  'A clareza sobre si mesmo se constrói aos poucos, não de uma vez.',
  'Reconhecer os próprios medos é o primeiro passo para lidar com eles.',
  'O autoconhecimento verdadeiro exige tempo sozinho com os próprios pensamentos.',
  'Toda mudança de comportamento começa com a percepção clara do comportamento atual.',
  'A honestidade interna evita o desgaste de manter aparências externas.',
  'Observar a própria mente sem se julgar é uma prática, não um dom.',
  'Conhecer os próprios valores facilita decisões difíceis mais tarde.',
  'Toda reflexão sincera exige abrir mão da imagem confortável que se tem de si.',
  'A calma interior nasce, em parte, do autoconhecimento bem cultivado.',
  'Reconhecer o que motiva as próprias ações é um exercício contínuo, não um evento único.',
  'O autoconhecimento amadurece com os erros observados sem autopunição.',
  'Toda pessoa que se conhece melhor toma decisões mais alinhadas com o que realmente quer.',
  'A prática de se observar com honestidade previne muitos arrependimentos futuros.',
  'Conhecer as próprias reações emocionais ajuda a responder, em vez de apenas reagir.',
  'Toda mudança interna começa antes de qualquer mudança visível para os outros.',
  'A observação paciente de si mesmo revela padrões que a pressa esconde.',
  'Reconhecer os próprios pontos fracos é tão útil quanto reconhecer os fortes.',
  'O autoconhecimento cresce quando se presta atenção aos próprios silêncios, não só às falas.',
  'Toda decisão alinhada com valores próprios costuma pesar menos no longo prazo.',
  'A clareza interna se constrói com perguntas sinceras feitas repetidamente.',
  'Observar como se reage à frustração ensina mais do que evitar a frustração.',
  'Conhecer a própria história ajuda a entender reações que pareciam sem explicação.',
  'Toda mudança de hábito exige primeiro reconhecer o hábito como ele realmente é.',
  'A honestidade consigo mesmo é incômoda no início e libertadora depois.',
  'Reconhecer os próprios progressos, por menores que sejam, fortalece a motivação real.',
  'O autoconhecimento é um processo contínuo, nunca um destino alcançado de vez.',
  'Observar-se com curiosidade, em vez de crítica, facilita mudanças mais duradouras.',
  'Toda escolha alinhada com o que se valoriza traz mais paz do que a escolha apressada.',
  'A pausa para refletir sobre si mesmo é tão produtiva quanto qualquer tarefa externa.',
  'Reconhecer os próprios limites de energia evita esgotamento desnecessário.',
  'O autoconhecimento amadurecido reduz a necessidade de aprovação externa constante.',
  'Toda mudança de comportamento sustentável começa com aceitação, não com autocrítica excessiva.',
  'Observar-se ao longo do tempo revela padrões que uma única reflexão não mostraria.',
  'Conhecer os próprios gatilhos emocionais é uma ferramenta prática, não apenas filosófica.',
  'Toda decisão tomada com autoconhecimento tende a exigir menos arrependimento depois.',
  'A calma para se observar sem pressa é, em si, uma forma de cuidado.',
  'Reconhecer-se em processo de mudança é mais realista do que esperar por uma versão final e pronta.',
  'O tempo bem usado importa mais do que o tempo apenas ocupado.',
  'Toda mudança profunda exige mais tempo do que a pressa gostaria de admitir.',
  'A paciência com o próprio ritmo evita comparações que só desanimam.',
  'Nem tudo que vale a pena acontece rápido, e está tudo bem assim.',
  'O tempo dedicado com constância rende mais do que o tempo gasto com pressa.',
  'Toda espera bem aproveitada prepara terreno para o momento certo de agir.',
  'A paciência não é passividade, é confiança no processo em andamento.',
  'Cada etapa cumprida no seu tempo evita retrabalho mais à frente.',
  'O tempo investido com atenção vale mais do que o tempo apenas contado.',
  'Toda pressa excessiva costuma custar mais tempo do que economiza.',
  'A paciência bem exercida transforma espera em preparação.',
  'Nem todo resultado aparece no tempo que se espera, e isso não invalida o esforço.',
  'O tempo dedicado a algo importante nunca é tempo perdido, mesmo sem resultado imediato.',
  'Toda jornada longa parece mais curta quando se aceita o próprio ritmo.',
  'A paciência com os próprios erros acelera, no fim, o próprio progresso.',
  'Cada minuto investido com foco vale mais do que uma hora gasta sem direção.',
  'O tempo certo para agir raramente é o tempo que a ansiedade escolheria.',
  'Toda espera consciente é diferente de uma espera vazia.',
  'A paciência aplicada ao aprendizado evita o desgaste da comparação constante.',
  'Nem tudo que demora está parado; muitas vezes está apenas amadurecendo.',
  'O tempo dedicado com regularidade supera o tempo gasto em rompantes ocasionais.',
  'Toda mudança sustentável respeita o tempo que o processo exige.',
  'A paciência é, muitas vezes, a diferença entre desistir cedo e colher tarde.',
  'Cada etapa cumprida sem pressa deixa uma base mais sólida para a próxima.',
  'O tempo gasto com atenção plena rende mais do que o tempo gasto distraído.',
  'Toda espera tem um propósito, mesmo quando esse propósito não é imediatamente visível.',
  'A paciência com o próprio processo é um exercício tão importante quanto qualquer prática técnica.',
  'Nem todo progresso é visível de imediato, mas isso não significa ausência de progresso.',
  'O tempo investido em entender bem economiza tempo de corrigir depois.',
  'Toda mudança de qualidade pede tempo que a pressa não costuma oferecer.',
  'A paciência aplicada evita decisões precipitadas tomadas por ansiedade.',
  'Cada fase cumprida em seu tempo próprio prepara melhor para a fase seguinte.',
  'O tempo dedicado com constância, mesmo pouco, supera o tempo intenso e raro.',
  'Toda espera bem vivida é também um tempo de preparação silenciosa.',
  'A paciência com o processo alheio é tão necessária quanto com o próprio.',
  'Nem tudo que é rápido é sólido, e nem tudo que é lento é fraco.',
  'O tempo certo de colher costuma vir depois do tempo certo de plantar.',
  'Toda jornada de longo prazo se sustenta em decisões pequenas tomadas com paciência.',
  'A paciência bem cultivada reduz a ansiedade sobre o que ainda não aconteceu.',
  'Cada momento de espera consciente pode ser também um momento de reflexão útil.',
  'O tempo investido em consolidar uma base evita retrocessos futuros.',
  'Toda mudança de hábito exige tempo suficiente para deixar de exigir esforço.',
  'A paciência com os próprios limites de energia é parte do cuidado consigo mesmo.',
  'Nem sempre o resultado mais rápido é o resultado mais duradouro.',
  'O tempo dedicado com regularidade constrói mais confiança do que o esforço isolado.',
  'Toda espera ativa, cheia de pequenas ações, é diferente de uma espera passiva.',
  'A paciência aplicada ao processo evita desistências motivadas pela pressa.',
  'Cada etapa vivida com atenção plena rende aprendizados que a pressa costuma ignorar.',
  'O tempo certo para cada mudança raramente coincide com o tempo que se deseja.',
  'Toda jornada bem conduzida respeita tanto a pressa necessária quanto a paciência devida.',
  'A liberdade real começa na escolha consciente, não na ausência de limites.',
  'Toda decisão tomada com clareza é também um exercício de liberdade.',
  'Escolher com atenção evita arrependimentos que a pressa costuma deixar para trás.',
  'A liberdade de escolher como reagir é, muitas vezes, a única liberdade totalmente disponível.',
  'Cada escolha consciente fortalece a capacidade de escolher melhor na próxima vez.',
  'A verdadeira autonomia nasce de decisões tomadas com responsabilidade, não por impulso.',
  'Toda liberdade exige, em algum grau, aceitar as consequências das próprias escolhas.',
  'Escolher o próprio caminho, mesmo incerto, vale mais do que seguir um caminho alheio com segurança.',
  'A liberdade de mudar de ideia é tão válida quanto a de manter uma decisão.',
  'Cada decisão tomada com consciência reduz o peso de decisões futuras semelhantes.',
  'A autonomia bem exercida respeita tanto os próprios limites quanto os limites dos outros.',
  'Toda escolha livre carrega também a responsabilidade pelo que ela gera.',
  'Escolher com calma evita decisões guiadas apenas pelo medo do momento.',
  'A liberdade de dizer não é tão importante quanto a liberdade de dizer sim.',
  'Cada escolha alinhada com valores próprios traz mais leveza do que a escolha por pressão externa.',
  'A verdadeira liberdade inclui a liberdade de errar e recomeçar.',
  'Toda decisão consciente é um ato de liberdade, mesmo quando difícil.',
  'Escolher devagar, quando possível, costuma trazer decisões mais sólidas.',
  'A liberdade de seguir o próprio ritmo é rara e, por isso, valiosa.',
  'Cada escolha feita com responsabilidade fortalece a confiança na própria capacidade de decidir.',
  'A autonomia amadurece com a prática de assumir as próprias decisões.',
  'Toda liberdade verdadeira aceita que nem todas as escolhas terão o resultado esperado.',
  'Escolher com base em valores próprios evita decisões guiadas apenas pela aprovação alheia.',
  'A liberdade de recomeçar é uma das mais subestimadas de todas.',
  'Cada decisão tomada com consciência plena vale mais do que várias tomadas no automático.',
  'A verdadeira autonomia respeita o tempo necessário para decidir bem.',
  'Toda escolha livre carrega o peso e o valor de ser genuinamente sua.',
  'Escolher o próprio caminho exige aceitar que nem todos vão concordar com ele.',
  'A liberdade de pausar antes de decidir é, muitas vezes, subestimada.',
  'Cada decisão tomada com responsabilidade fortalece o senso de propósito.',
  'A autonomia bem exercida não depende da aprovação constante dos outros.',
  'Toda escolha consciente é também uma forma de autorrespeito.',
  'Escolher com atenção ao próprio bem-estar não é egoísmo, é cuidado.',
  'A liberdade de errar sem se punir excessivamente é essencial para qualquer progresso.',
  'Cada decisão alinhada com o que realmente importa traz mais clareza para as próximas.',
  'A verdadeira liberdade inclui a liberdade de pedir ajuda quando necessário.',
  'Toda escolha tomada com calma tende a exigir menos correções depois.',
  'Escolher devagar em decisões importantes evita arrependimentos apressados.',
  'A liberdade de definir as próprias prioridades é um exercício constante, não um estado fixo.',
  'Cada decisão consciente contribui para uma vida mais alinhada com o que se valoriza.',
  'A autonomia madura aceita tanto o sucesso quanto o fracasso como parte do processo.',
  'Toda liberdade exercida com responsabilidade fortalece a confiança nas próprias escolhas.',
  'Escolher com base em experiência própria vale mais do que escolher só por comparação.',
  'A liberdade de seguir devagar, quando necessário, é tão legítima quanto a de acelerar.',
  'Cada decisão tomada com honestidade interna facilita decisões futuras semelhantes.',
  'A verdadeira autonomia aceita que nem toda escolha precisa ser perfeita para ser válida.',
  'Toda escolha consciente contribui, aos poucos, para uma vida mais coerente com valores próprios.',
  'Escolher com paciência evita decisões motivadas apenas pela pressa do momento.',
  'A liberdade de reavaliar decisões antigas é parte saudável de qualquer autonomia.',
  'Cada decisão tomada com responsabilidade constrói, aos poucos, uma vida mais alinhada consigo mesmo.',
  'A clareza nasce, quase sempre, da simplicidade bem cultivada.',
  'Fazer menos coisas com mais atenção supera fazer muitas coisas pela metade.',
  'Toda ideia complexa se explica melhor quando reduzida ao essencial.',
  'A simplicidade bem pensada exige mais esforço do que a complexidade improvisada.',
  'Eliminar o supérfluo deixa espaço para o que realmente importa.',
  'Toda clareza real começa com a coragem de simplificar.',
  'Fazer o básico muito bem vale mais do que fazer o avançado pela metade.',
  'A simplicidade não é ausência de profundidade, é profundidade bem organizada.',
  'Reduzir o desnecessário libera energia para o que traz resultado de verdade.',
  'Toda tarefa clara começa com um objetivo simples e bem definido.',
  'A clareza mental se constrói removendo, não acumulando.',
  'Fazer poucas coisas com excelência supera fazer muitas com mediocridade.',
  'A simplicidade bem aplicada facilita tanto o aprendizado quanto o ensino.',
  'Toda solução elegante costuma ser, no fundo, uma solução simples bem executada.',
  'Reduzir distrações é uma forma prática de buscar clareza.',
  'A clareza de propósito facilita decisões que antes pareciam complicadas.',
  'Fazer menos, mas com intenção, rende mais do que fazer muito sem direção.',
  'A simplicidade bem cultivada é, muitas vezes, o resultado de bastante prática.',
  'Toda ideia clara pode ser explicada de forma simples, mesmo sendo profunda.',
  'Reduzir o ruído externo ajuda a enxergar o que realmente precisa de atenção.',
  'A clareza sobre prioridades evita o desgaste de tentar fazer tudo ao mesmo tempo.',
  'Fazer uma coisa de cada vez, com atenção plena, é uma forma prática de simplicidade.',
  'A simplicidade verdadeira exige entender profundamente antes de conseguir simplificar.',
  'Toda mudança sustentável costuma começar com passos simples e bem definidos.',
  'Reduzir o excesso de opções facilita decisões mais rápidas e mais seguras.',
  'A clareza de objetivo transforma esforço disperso em progresso direcionado.',
  'Fazer o simples com constância supera fazer o complexo de forma esporádica.',
  'A simplicidade bem pensada respeita o tempo e a energia de quem a pratica.',
  'Toda tarefa bem definida é mais fácil de cumprir do que uma tarefa vaga.',
  'Reduzir para o essencial ajuda a enxergar o que realmente traz resultado.',
  'A clareza interna reduz a necessidade de decisões constantes sobre o óbvio.',
  'Fazer menos promessas e cumprir todas vale mais do que prometer muito e cumprir pouco.',
  'A simplicidade bem aplicada facilita tanto a prática quanto a avaliação do progresso.',
  'Toda ideia bem simplificada se torna mais fácil de lembrar e de aplicar.',
  'Reduzir o supérfluo no dia a dia libera espaço para o que importa de verdade.',
  'A clareza de propósito sustenta a motivação nos dias mais difíceis.',
  'Fazer uma tarefa simples com excelência ensina mais do que várias feitas com pressa.',
  'A simplicidade bem cultivada exige disciplina para não voltar ao excesso.',
  'Toda mudança clara começa com a definição simples do que se quer alcançar.',
  'Reduzir a complexidade desnecessária é, muitas vezes, o primeiro passo para o progresso.',
  'A clareza sobre o que realmente importa facilita dizer não ao resto.',
  'Fazer menos coisas, mas melhor feitas, constrói mais confiança do que fazer muitas pela metade.',
  'A simplicidade bem pensada é, no fundo, uma forma de respeito pelo próprio tempo.',
  'Toda tarefa simplificada corretamente se torna mais fácil de repetir com constância.',
  'Reduzir o desnecessário no processo deixa mais espaço para o essencial.',
  'A clareza de metas simples facilita medir o progresso real.',
  'Fazer o básico com excelência é, muitas vezes, mais raro do que fazer o avançado.',
  'A simplicidade bem aplicada evita o desgaste de decisões complicadas demais.',
  'Toda prática simplificada tende a ser mais sustentável no longo prazo.',
  'Reduzir para o essencial é, ao mesmo tempo, um exercício de clareza e de coragem.',
  'Todo crescimento real exige desconforto antes de trazer conforto.',
  'A transformação verdadeira acontece aos poucos, mesmo quando parece súbita de fora.',
  'Crescer é aceitar que a versão de ontem já não serve para hoje.',
  'Toda mudança duradoura começa dentro, antes de aparecer para os outros.',
  'O crescimento constante exige revisar crenças antigas com honestidade.',
  'Transformar-se é, no fundo, aprender a se despedir de hábitos que já não ajudam.',
  'Toda evolução pessoal pede tempo, paciência e disposição para recomeçar.',
  'Crescer significa, muitas vezes, sair do que é confortável para o que é necessário.',
  'A transformação sólida se constrói com pequenas mudanças sustentadas no tempo.',
  'Todo processo de crescimento inclui etapas de dúvida e desorientação temporária.',
  'Mudar de verdade exige mais do que intenção, exige prática repetida.',
  'O crescimento pessoal amadurece quando se aceita o próprio ritmo, sem comparação excessiva.',
  'Toda transformação começa com a decisão de olhar para si mesmo com honestidade.',
  'Crescer é acumular experiências e, principalmente, aprender com elas.',
  'A evolução constante exige revisar, de tempos em tempos, o próprio caminho.',
  'Toda mudança significativa pede coragem para abandonar o que já não serve.',
  'Transformar-se aos poucos costuma ser mais sustentável do que mudar de uma vez.',
  'O crescimento verdadeiro aparece na forma como se reage aos desafios, não apenas no resultado final.',
  'Toda pessoa em transformação passa por fases de incerteza que fazem parte do processo.',
  'Crescer exige, muitas vezes, deixar para trás certezas que pareciam definitivas.',
  'A transformação pessoal amadurece com o tempo, não com pressa.',
  'Todo processo de crescimento pede espaço para tentar, errar e ajustar.',
  'Mudar hábitos antigos exige mais repetição consciente do que força de vontade isolada.',
  'O crescimento sustentável respeita os próprios limites, sem deixar de desafiá-los.',
  'Toda transformação real deixa marcas visíveis apenas depois de um tempo de trabalho invisível.',
  'Crescer é, também, aprender a lidar melhor com o desconforto da mudança.',
  'A evolução pessoal se fortalece quando se aprende com os próprios retrocessos.',
  'Todo caminho de transformação inclui momentos de recuo antes de novos avanços.',
  'Mudar de direção quando necessário é parte saudável de qualquer crescimento.',
  'O crescimento verdadeiro se mede mais pela constância do que pela velocidade.',
  'Toda pessoa em processo de mudança precisa de paciência consigo mesma.',
  'Crescer exige aceitar que nem todo esforço trará resultado imediato.',
  'A transformação pessoal se sustenta em decisões pequenas, repetidas com constância.',
  'Todo processo de evolução pede espaço para revisar e ajustar o percurso.',
  'Mudar de verdade exige encarar de frente aquilo que se prefere evitar.',
  'O crescimento contínuo se apoia tanto nos acertos quanto nos erros bem observados.',
  'Toda transformação sólida exige tempo suficiente para se consolidar de fato.',
  'Crescer é, no fundo, tornar-se capaz de lidar com desafios que antes pareciam grandes demais.',
  'A evolução pessoal amadurece quando se aprende a celebrar pequenos avanços.',
  'Todo caminho de crescimento inclui etapas que parecem, por um tempo, sem progresso visível.',
  'Mudar de comportamento exige repetição paciente, não apenas boa intenção.',
  'O crescimento verdadeiro respeita tanto os avanços quanto as pausas necessárias.',
  'Toda transformação pessoal se fortalece quando apoiada em hábitos simples e constantes.',
  'Crescer significa, muitas vezes, ampliar a capacidade de tolerar o desconforto temporário.',
  'A evolução constante exige revisar metas conforme a experiência acumulada.',
  'Todo processo de mudança pede espaço para o erro como parte do aprendizado.',
  'Transformar-se de verdade é um trabalho contínuo, nunca um evento único.',
  'O crescimento pessoal amadurece quando se aprende a confiar no próprio processo.',
  'Toda mudança duradoura nasce de pequenas decisões repetidas com paciência e constância.',
  'Crescer é, ao final, tornar-se capaz de recomeçar com mais clareza do que antes.',
];

export function normalizeAscii(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .trim();
}

// Fonte de verdade legível (com acentos). Corpus completo de 500 frases fornecido pelo produto.
export const PT_BR_PHRASES_RAW: readonly string[] = STARTER_PHRASES;

// Versão normalizada (ASCII) efetivamente usada na geração de reforço.
export const PT_BR_PHRASES: readonly string[] = STARTER_PHRASES.map(normalizeAscii).filter(
  phrase => phrase.length > 0
);