export const adaptiveParams = {
  WEAK_POOL_WEIGHT: 0.60,
  CONSOLIDATING_POOL_WEIGHT: 0.25,
  MASTERED_POOL_WEIGHT: 0.15,
  MASTERY_ACCURACY: 0.95,
  MASTERY_ATTEMPTS: 30,
  MASTERY_LATENCY_MS: 500,
  MASTERY_CONSECUTIVE_SESSIONS: 3,
  UNKNOWN_ATTEMPTS: 5,
  LATENCY_REFERENCE_MS: 500,
  WEAK_THRESHOLD: 0.70,
  CONSOLIDATING_THRESHOLD: 0.40,
  RECENCY_LAMBDA: 0.1,
  REINFORCEMENT_TARGET_CHARACTERS: 150,
  ACTIVE_DURATION_EPSILON_MS: 1000,
  LESSON_MASTERY_ACCURACY: 0.95,
  LESSON_REVIEW_ACCURACY: 0.60,
  LESSON_REVIEW_MIN_ATTEMPTS: 2,

  // RN33 - pacing de prática: bloco de 15 min de prática ativa → pausa mínima de 3 min
  PRACTICE_BLOCK_DURATION_MS: 900000,
  MIN_BREAK_DURATION_MS: 180000,
} as const;

export type AdaptiveParams = typeof adaptiveParams;