export const adaptiveParams = {
  WEAK_POOL_WEIGHT: 0.60,
  CONSOLIDATING_POOL_WEIGHT: 0.25,
  MASTERED_POOL_WEIGHT: 0.15,
  MASTERY_ACCURACY: 0.95,
  MASTERY_ATTEMPTS: 30,
  MASTERY_LATENCY_MS: 500,
  MASTERY_CONSECUTIVE_SESSIONS: 3,
  UNKNOWN_ATTEMPTS: 5,
  LATENCY_REFERENCE_MS: 500,
  WEAK_THRESHOLD: 0.70,
  CONSOLIDATING_THRESHOLD: 0.40,
  RECENCY_LAMBDA: 0.1,
  REINFORCEMENT_TARGET_CHARACTERS: 150,
  ACTIVE_DURATION_EPSILON_MS: 1000,
} as const;

export type AdaptiveParams = typeof adaptiveParams;